#include <crtdbg.h>
#include <list>
#include <map>
#include <cuda.h>
#include <cuda_runtime.h> // cudaError_t, CUDARTAPI, etc.

class NVIDIA_GPU : DEVICE
{
public:
    NVIDIA_GPU();
    ~NVIDIA_GPU();

    void** _cudaRegisterFatBinary(void *fatCubin);
    virtual cudaError_t _cudaMalloc(void ** ptr, size_t size);
    virtual cudaError_t _cudaGetLastError();

    // cuda.h equivalents.
    virtual CUresult _cuArray3DCreate(CUarray *pHandle, const CUDA_ARRAY3D_DESCRIPTOR *pAllocateArray);
    virtual CUresult _cuArray3DCreate_v2(CUarray *pHandle, const CUDA_ARRAY3D_DESCRIPTOR *pAllocateArray);
    virtual CUresult _cuArray3DGetDescriptor_v2( CUDA_ARRAY3D_DESCRIPTOR *pArrayDescriptor, CUarray hArray );
    virtual CUresult _cuArray3DGetDescriptor( CUDA_ARRAY3D_DESCRIPTOR *pArrayDescriptor, CUarray hArray );
    virtual CUresult _cuArrayCreate( CUarray *pHandle, const CUDA_ARRAY_DESCRIPTOR *pAllocateArray );
    virtual CUresult _cuArrayCreate_v2( CUarray *pHandle, const CUDA_ARRAY_DESCRIPTOR *pAllocateArray );
    virtual CUresult _cuArrayDestroy( CUarray hArray );
    virtual CUresult _cuArrayGetDescriptor( CUDA_ARRAY_DESCRIPTOR *pArrayDescriptor, CUarray hArray );
    virtual CUresult _cuArrayGetDescriptor_v2( CUDA_ARRAY_DESCRIPTOR *pArrayDescriptor, CUarray hArray );
    virtual CUresult _cuCtxAttach(CUcontext *pctx, unsigned int flags);
    virtual CUresult _cuCtxCreate(CUcontext *pctx, unsigned int flags, CUdevice dev );
    virtual CUresult _cuCtxCreate_v2(CUcontext *pctx, unsigned int flags, CUdevice dev );
    virtual CUresult _cuCtxDestroy( CUcontext ctx );
    virtual CUresult _cuCtxDetach(CUcontext ctx);
    virtual CUresult _cuCtxGetDevice(CUdevice *device);
    virtual CUresult _cuCtxGetLimit(size_t *pvalue, CUlimit limit);
    virtual CUresult _cuCtxPopCurrent( CUcontext *pctx );
    virtual CUresult _cuCtxPushCurrent( CUcontext ctx );
    virtual CUresult _cuCtxSetLimit(CUlimit limit, size_t value);
    virtual CUresult _cuCtxSynchronize(void);
    virtual CUresult _cuDeviceComputeCapability(int *major, int *minor, CUdevice dev);
    virtual CUresult _cuDeviceGet(CUdevice *device, int ordinal);
    virtual CUresult _cuDeviceGetAttribute(int *pi, CUdevice_attribute attrib, CUdevice dev);
    virtual CUresult _cuDeviceGetCount(int *count);
    virtual CUresult _cuDeviceGetName(char *name, int len, CUdevice dev);
    virtual CUresult _cuDeviceGetProperties(CUdevprop *prop, CUdevice dev);
    virtual CUresult _cuDeviceTotalMem(unsigned int *bytes, CUdevice dev);
    virtual CUresult _cuDeviceTotalMem_v2(unsigned int *bytes, CUdevice dev);
    virtual CUresult _cuDriverGetVersion(int *driverVersion);
    virtual CUresult _cuEventCreate( CUevent *phEvent, unsigned int Flags );
    virtual CUresult _cuEventDestroy( CUevent hEvent );
    virtual CUresult _cuEventElapsedTime( float *pMilliseconds, CUevent hStart, CUevent hEnd );
    virtual CUresult _cuEventQuery( CUevent hEvent );
    virtual CUresult _cuEventRecord( CUevent hEvent, CUstream hStream );
    virtual CUresult _cuEventSynchronize( CUevent hEvent );
    virtual CUresult _cuFuncGetAttribute (int *pi, CUfunction_attribute attrib, CUfunction hfunc);
    virtual CUresult _cuFuncSetBlockShape (CUfunction hfunc, int x, int y, int z);
    virtual CUresult _cuFuncSetCacheConfig(CUfunction hfunc, CUfunc_cache config);
    virtual CUresult _cuFuncSetSharedSize (CUfunction hfunc, unsigned int bytes);
    virtual CUresult _cuGetExportTable( const void **ppExportTable, const CUuuid *pExportTableId );
    virtual CUresult _cuGraphicsMapResources( unsigned int count, CUgraphicsResource *resources, CUstream hStream );
    virtual CUresult _cuGraphicsResourceGetMappedPointer( CUdeviceptr *pDevPtr, unsigned int *pSize, CUgraphicsResource resource );
    virtual CUresult _cuGraphicsResourceGetMappedPointer_v2( CUdeviceptr *pDevPtr, unsigned int *pSize, CUgraphicsResource resource );
    virtual CUresult _cuGraphicsResourceSetMapFlags( CUgraphicsResource resource, unsigned int flags );
    virtual CUresult _cuGraphicsSubResourceGetMappedArray( CUarray *pArray, CUgraphicsResource resource, unsigned int arrayIndex, unsigned int mipLevel );
    virtual CUresult _cuGraphicsUnmapResources( unsigned int count, CUgraphicsResource *resources, CUstream hStream );
    virtual CUresult _cuGraphicsUnregisterResource(CUgraphicsResource resource);
    virtual CUresult _cuInit(unsigned int Flags);
    virtual CUresult _cuLaunch ( CUfunction f );
    virtual CUresult _cuLaunchGrid (CUfunction f, int grid_width, int grid_height);
    virtual CUresult _cuLaunchGridAsync( CUfunction f, int grid_width, int grid_height, CUstream hStream );
    virtual CUresult _cuMemAlloc( CUdeviceptr *dptr, unsigned int bytesize);
    virtual CUresult _cuMemAlloc_v2( CUdeviceptr *dptr, unsigned int bytesize);
    virtual CUresult _cuMemAllocHost(void **pp, unsigned int bytesize);
    virtual CUresult _cuMemAllocHost_v2(void **pp, unsigned int bytesize);
    virtual CUresult _cuMemAllocPitch( CUdeviceptr *dptr, unsigned int *pPitch, unsigned int WidthInBytes, unsigned int Height, unsigned int ElementSizeBytes);
    virtual CUresult _cuMemAllocPitch_v2( CUdeviceptr *dptr, unsigned int *pPitch, unsigned int WidthInBytes, unsigned int Height, unsigned int ElementSizeBytes);
    virtual CUresult _cuMemcpy2D( const CUDA_MEMCPY2D *pCopy );
    virtual CUresult _cuMemcpy2D_v2( const CUDA_MEMCPY2D *pCopy );
    virtual CUresult _cuMemcpy2DAsync( const CUDA_MEMCPY2D *pCopy, CUstream hStream );
    virtual CUresult _cuMemcpy2DAsync_v2( const CUDA_MEMCPY2D *pCopy, CUstream hStream );
    virtual CUresult _cuMemcpy2DUnaligned( const CUDA_MEMCPY2D *pCopy );
    virtual CUresult _cuMemcpy2DUnaligned_v2( const CUDA_MEMCPY2D *pCopy );
    virtual CUresult _cuMemcpy3D( const CUDA_MEMCPY3D *pCopy );
    virtual CUresult _cuMemcpy3D_v2( const CUDA_MEMCPY3D *pCopy );
    virtual CUresult _cuMemcpy3DAsync( const CUDA_MEMCPY3D *pCopy, CUstream hStream );
    virtual CUresult _cuMemcpy3DAsync_v2( const CUDA_MEMCPY3D *pCopy, CUstream hStream );
    virtual CUresult _cuMemcpyAtoA( CUarray dstArray, unsigned int dstOffset, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoA_v2( CUarray dstArray, unsigned int dstOffset, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoD ( CUdeviceptr dstDevice, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoD_v2 ( CUdeviceptr dstDevice, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoH( void *dstHost, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoH_v2( void *dstHost, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount );
    virtual CUresult _cuMemcpyAtoHAsync( void *dstHost, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyAtoHAsync_v2( void *dstHost, CUarray srcArray, unsigned int srcOffset, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyDtoA ( CUarray dstArray, unsigned int dstOffset, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoA_v2 ( CUarray dstArray, unsigned int dstOffset, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoD (CUdeviceptr dstDevice, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoD_v2 (CUdeviceptr dstDevice, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoDAsync (CUdeviceptr dstDevice, CUdeviceptr srcDevice, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyDtoDAsync_v2 (CUdeviceptr dstDevice, CUdeviceptr srcDevice, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyDtoH (void *dstHost, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoH_v2 (void *dstHost, CUdeviceptr srcDevice, unsigned int ByteCount );
    virtual CUresult _cuMemcpyDtoHAsync (void *dstHost, CUdeviceptr srcDevice, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyDtoHAsync_v2 (void *dstHost, CUdeviceptr srcDevice, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyHtoA( CUarray dstArray, unsigned int dstOffset, const void *srcHost, unsigned int ByteCount );
    virtual CUresult _cuMemcpyHtoA_v2( CUarray dstArray, unsigned int dstOffset, const void *srcHost, unsigned int ByteCount );
    virtual CUresult _cuMemcpyHtoAAsync( CUarray dstArray, unsigned int dstOffset, const void *srcHost, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyHtoAAsync_v2( CUarray dstArray, unsigned int dstOffset, const void *srcHost, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyHtoD (CUdeviceptr dstDevice, const void *srcHost, unsigned int ByteCount );
    virtual CUresult _cuMemcpyHtoD_v2 (CUdeviceptr dstDevice, const void *srcHost, unsigned int ByteCount );
    virtual CUresult _cuMemcpyHtoDAsync (CUdeviceptr dstDevice, const void *srcHost, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemcpyHtoDAsync_v2 (CUdeviceptr dstDevice, const void *srcHost, unsigned int ByteCount, CUstream hStream );
    virtual CUresult _cuMemFree(CUdeviceptr dptr);
    virtual CUresult _cuMemFree_v2(CUdeviceptr dptr);
    virtual CUresult _cuMemFreeHost(void *p);
    virtual CUresult _cuMemGetAddressRange( CUdeviceptr *pbase, unsigned int *psize, CUdeviceptr dptr );
    virtual CUresult _cuMemGetAddressRange_v2( CUdeviceptr *pbase, unsigned int *psize, CUdeviceptr dptr );
    virtual CUresult _cuMemGetInfo(unsigned int *free, unsigned int *total);
    virtual CUresult _cuMemGetInfo_v2(unsigned int *free, unsigned int *total);
    virtual CUresult _cuMemHostAlloc(void **pp, size_t bytesize, unsigned int Flags );
    virtual CUresult _cuMemHostGetDevicePointer( CUdeviceptr *pdptr, void *p, unsigned int Flags );
    virtual CUresult _cuMemHostGetDevicePointer_v2( CUdeviceptr *pdptr, void *p, unsigned int Flags );
    virtual CUresult _cuMemHostGetFlags( unsigned int *pFlags, void *p );
    virtual CUresult _cuMemsetD16( CUdeviceptr dstDevice, unsigned short us, unsigned int N );
    virtual CUresult _cuMemsetD16_v2( CUdeviceptr dstDevice, unsigned short us, unsigned int N );
    virtual CUresult _cuMemsetD2D16( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned short us, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD2D16_v2( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned short us, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD2D32( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned int ui, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD2D32_v2( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned int ui, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD2D8( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned char uc, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD2D8_v2( CUdeviceptr dstDevice, unsigned int dstPitch, unsigned char uc, unsigned int Width, unsigned int Height );
    virtual CUresult _cuMemsetD32( CUdeviceptr dstDevice, unsigned int ui, unsigned int N );
    virtual CUresult _cuMemsetD32_v2( CUdeviceptr dstDevice, unsigned int ui, unsigned int N );
    virtual CUresult _cuMemsetD8( CUdeviceptr dstDevice, unsigned char uc, unsigned int N );
    virtual CUresult _cuMemsetD8_v2( CUdeviceptr dstDevice, unsigned char uc, unsigned int N );
    virtual CUresult _cuModuleGetFunction(CUfunction *hfunc, CUmodule hmod, const char *name);
    virtual CUresult _cuModuleGetGlobal(CUdeviceptr *dptr, unsigned int *bytes, CUmodule hmod, const char *name);
    virtual CUresult _cuModuleGetGlobal_v2(CUdeviceptr *dptr, unsigned int *bytes, CUmodule hmod, const char *name);
    virtual CUresult _cuModuleGetSurfRef(CUsurfref *pSurfRef, CUmodule hmod, const char *name);
    virtual CUresult _cuModuleGetTexRef(CUtexref *pTexRef, CUmodule hmod, const char *name);
    virtual CUresult _cuModuleLoad(CUmodule *module, const char *fname);
    virtual CUresult _cuModuleLoadData(CUmodule *module, const void *image);
    virtual CUresult _cuModuleLoadDataEx(CUmodule *module, const void *image, unsigned int numOptions, CUjit_option *options, void **optionValues);
    virtual CUresult _cuModuleLoadFatBinary(CUmodule *module, const void *fatCubin);
    virtual CUresult _cuModuleUnload(CUmodule hmod);
    virtual CUresult _cuParamSetf    (CUfunction hfunc, int offset, float value);
    virtual CUresult _cuParamSeti    (CUfunction hfunc, int offset, unsigned int value);
    virtual CUresult _cuParamSetSize (CUfunction hfunc, unsigned int numbytes);
    virtual CUresult _cuParamSetTexRef(CUfunction hfunc, int texunit, CUtexref hTexRef);
    virtual CUresult _cuParamSetv    (CUfunction hfunc, int offset, void *ptr, unsigned int numbytes);
    virtual CUresult _cuStreamCreate( CUstream *phStream, unsigned int Flags );
    virtual CUresult _cuStreamDestroy( CUstream hStream );
    virtual CUresult _cuStreamQuery( CUstream hStream );
    virtual CUresult _cuStreamSynchronize( CUstream hStream );
    virtual CUresult _cuSurfRefGetArray( CUarray *phArray, CUsurfref hSurfRef );
    virtual CUresult _cuSurfRefSetArray( CUsurfref hSurfRef, CUarray hArray, unsigned int Flags );
    virtual CUresult _cuTexRefCreate( CUtexref *pTexRef );
    virtual CUresult _cuTexRefDestroy( CUtexref hTexRef );
    virtual CUresult _cuTexRefGetAddress( CUdeviceptr *pdptr, CUtexref hTexRef );
    virtual CUresult _cuTexRefGetAddress_v2( CUdeviceptr *pdptr, CUtexref hTexRef );
    virtual CUresult _cuTexRefGetAddressMode( CUaddress_mode *pam, CUtexref hTexRef, int dim );
    virtual CUresult _cuTexRefGetArray( CUarray *phArray, CUtexref hTexRef );
    virtual CUresult _cuTexRefGetFilterMode( CUfilter_mode *pfm, CUtexref hTexRef );
    virtual CUresult _cuTexRefGetFlags( unsigned int *pFlags, CUtexref hTexRef );
    virtual CUresult _cuTexRefGetFormat( CUarray_format *pFormat, int *pNumChannels, CUtexref hTexRef );
    virtual CUresult _cuTexRefSetAddress( unsigned int *ByteOffset, CUtexref hTexRef, CUdeviceptr dptr, unsigned int bytes );
    virtual CUresult _cuTexRefSetAddress_v2( unsigned int *ByteOffset, CUtexref hTexRef, CUdeviceptr dptr, unsigned int bytes );
    virtual CUresult _cuTexRefSetAddress2D( CUtexref hTexRef, const CUDA_ARRAY_DESCRIPTOR *desc, CUdeviceptr dptr, unsigned int Pitch);
    virtual CUresult _cuTexRefSetAddress2D_v2( CUtexref hTexRef, const CUDA_ARRAY_DESCRIPTOR *desc, CUdeviceptr dptr, unsigned int Pitch);
    virtual CUresult _cuTexRefSetAddressMode( CUtexref hTexRef, int dim, CUaddress_mode am );
    virtual CUresult _cuTexRefSetArray( CUtexref hTexRef, CUarray hArray, unsigned int Flags );
    virtual CUresult _cuTexRefSetFilterMode( CUtexref hTexRef, CUfilter_mode fm );
    virtual CUresult _cuTexRefSetFlags( CUtexref hTexRef, unsigned int Flags );
    virtual CUresult _cuTexRefSetFormat( CUtexref hTexRef, CUarray_format fmt, int );

    void ExitHandler();
};

